In [2]:
#test
import numpy as np 
a=np.array([1, 2, 3, 4, 5])
b=np.array([5,7, 13,8,9])
print(a+b)

[ 6  9 16 12 14]


# Question 1

In [10]:
import numpy as np
tab= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f'NumPy Array: {tab}')
print(type(tab))

list1 = tab.tolist()
print(f'List: {list1}')
print(type(list1))


NumPy Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
List: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
<class 'list'>


# Question 2

In [48]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:",m)
result =  np.trace(m)
print("\n la somme des éléments diagonaux de la matrice est",result)

Original matrix: [[0 1 2]
 [3 4 5]]

 la somme des éléments diagonaux de la matrice est 4


In [73]:
import numpy as np
m = np.arange(9).reshape(3,3)
print("Original matrix:")
print(m)
z = 0
for i in range(3):
    z += m[i,i]
print("la somme des éléments diagonaux de la matrice est",z)

Original matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
la somme des éléments diagonaux de la matrice est 12


# Question 3

In [25]:
import numpy as np
tab= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
x = int(input("Choisissez une valeur appartenant a la matrice tab "))
print(tab)
result = []
for i in tab:
    for z in i:
        if(z >= x):
            result.append(z) 
print("alors voici tous les éléments appartenant au tab qu isont supérieur à x",result)

Choisissez une valeur appartenant a la matrice tab 3
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
alors voici tous les éléments appartenant au tab qu isont supérieur à x [3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


# Question 4

In [60]:
import numpy as np
A=np.random.randint(2, 19, size=(3,5))
print(A)

B = np.random.randint(6, 14, size=(3,5))
print("\n",B)

C =np.add(A,B) #ou C= A+B 
print("\n",C)

#x=np.array([[1,2],[3,4]], dtype=np.int32)
#print(x)

[[16 18  9  6  6]
 [14 11  5 12 10]
 [ 6  5  6  4  9]]

 [[ 6  7  8  7 12]
 [12  9  7  7  6]
 [ 7 11  6  7  7]]

 [[22 25 17 13 18]
 [26 20 12 19 16]
 [13 16 12 11 16]]


# Question 5

In [86]:
import numpy as np
matrice1 = np.random.randint(2, 19, size=(3,5))
print(matrice1)
New_Tab = np.mean(matrice1, axis = 1)
print("\n The mean of the array when axis = 1 : ", New_Tab)
list1 = New_Tab.tolist()
print(f'List: {list1}')
index = 0
for i in matrice1 : 
    index2 = 0
    for j in i:
        matrice1[index,index2] -= round(list1[index])
        index2 += 1
    index += 1
print(matrice1)

[[ 8 16 15  2 16]
 [ 5 14 18 11 10]
 [ 8  7 18 17 18]]

 The mean of the array when axis = 1 :  [11.4 11.6 13.6]
List: [11.4, 11.6, 13.6]
[[-3  5  4 -9  5]
 [-7  2  6 -1 -2]
 [-6 -7  4  3  4]]
